# Simple Kubernetes Pod to deploy the app contained in debaranjan/kubernetess:1.0
apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: debaranjan/kubernetess:1.0
      ports:
        - containerPort: 8080
